### ISSUE TITLE
Frage zum Vorgehen in unserem Projekt

### ISSUE THREAD

**Issue by RichardReh** [RichardReh/EPWS2122RehMisenkoBerg#6]
Hallo zusammen,
wir sind dabei unser Projekt umzusetzen aber sind dabei auf eine Sache gestoßen. Es geht darum, dass wir ja eine Session zwischen mehreren Nutzern erstellen möchten, damit diese wiederum in der Session Informationen austauschen können (in unserem Fall Bilder und HTML-Canvas Strokes). Wir haben aber dabei noch folgendes Problem: es sollte eine Art Live-Session entstehen, sodass die auszutauschenden Informationen direkt an alle Nutzer in einer Session übermittelt werden. Wir ,,könnten" entweder die Bildinformationen eher asynchron senden, was bedeutet, dass wenn jemand das Bild mit einem Stift kommentiert, die Canvas-Informationen dann nach jedem Mal wenn die Maus losgelöst wird wie ein Event lossenden damit alle anderen Nutzer die Information dann erhalten. 

Oder wir haben eine richtige Peer to Peer Kommunikation, welche zwar auch den Zeichnungsvorgang mitsenden würde aber dafür sehr schwer umzusetzen ist.

Wir würden daher gerne dazu fragen was genau nun doch besser wäre, da wir es ja letztendlich auch am Ende umsetzen können müssen.

Vielen Dank im Voraus,
Reh, Misenko, Berg

**Comment by mariofaske** [comment]
Hallo,

wie du schon sagst, müsst ihr es auch umsetzen können. Natürlich solltet ihr klarmachen, warum es für euch sehr schwer umzusetzen ist. 

Wenn die asynchrone Variante einfacher ist, dann setzt die erstmal um, damit ihr euer Ziel erreicht. Jedoch wäre es gut, wenn ihr Alternativen genauer betrachtet und eventuell auch mal rudimentär umsetzt beziehungsweise konzeptionell ausarbeitet.

**Comment by vschaefer** [comment]
Ich bin da da bei Mario. Es wäre gut wenn ihr die unterschiedlichen Ansätze dokumentiert und gegeneinander abwägt. Hier sollte man aus meiner Sicht auch in Betracht ziehen, wenn mehr als zwei Personen miteinander interagieren.
